CREATE TABLE IF NOT EXISTS `UsersLocations`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` VARCHAR(25) NOT NULL,
	`user_location` VARCHAR(255) NOT NULL,
	`user_ip` VARCHAR(45) NOT NULL,
	`date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 DEFAULT COLLATE=UTF8_UNICODE_CI;
